img-mngr-mysql:
  image: mysql:5.7
  container_name: img_mngr_dev_mysql
  environment:
    MYSQL_DATABASE: img_mngr
    MYSQL_ROOT_PASSWORD: qwe909qwe
    MYSQL_USER: admin
    MYSQL_PASSWORD: zxc909zxc

fs-image-manager:
  image: imyousuf/fs-image-manager:latest
  links:
    - img-mngr-mysql:mysql
  ports:
    - "10080:8080"
  volumes:
    - ./main.go:/go/src/github.com/imyousuf/fs-image-manager/main.go
    - ./Makefile:/go/src/github.com/imyousuf/fs-image-manager/Makefile
    - ./app:/go/src/github.com/imyousuf/fs-image-manager/app/
    - ./web:/go/src/github.com/imyousuf/fs-image-manager/web/
    - ~/Pictures/:/path/to/images_dir
